### ISSUE TITLE
Do you plan any RESTful support?

### ISSUE THREAD

**Issue by sirop** [cybercatalyst/qtwebserver#9]
Do you plan any RESTful support?

Just out of curiosity.

**Comment by cybercatalyst** [comment]
REST should already be possible. In fact, the whole paradigm of QtWebServer is resource-centric. Not sure if I got your question right, though.

**Comment by sirop** [comment]
I looked at https://github.com/cybercatalyst/qtwebserver-examples/blob/master/minimal/main.cpp  right now. You are right again.

I got confused  the other day as on can find a whole RESTful SDK on the net...
But you have everything within the Qt server. :)
